### ISSUE TITLE
Please add Group item

### ISSUE THREAD

**Issue by 0x0021** [ptrkstr/QuickConnect#1]
Please add SSL VPN group item, thank you

**Comment by ptrkstr** [comment]
Hi there, can you provide more information on what that is? Is this something that is prompted to you when you use AnyConnect?

**Comment by 0x0021** [comment]
> 
![](https://i.loli.net/2021/11/29/yLjH4gAib1wZtF6.png)

**Comment by ptrkstr** [comment]
Thank you for responding so quickly.
Unfortunately I don't have access to a VPN that asks for that.
Can I suggest you run the following in terminal and paste what you see (remembering to redact anything)?
Replace {address} with your actual address
```
/opt/cisco/anyconnect/bin/vpn -s connect {address}
```

**Comment by 0x0021** [comment]
![image](https://user-images.githubusercontent.com/3069412/143967094-c7f2a0aa-5a4f-4c90-8bb5-a67e99f96d11.png)

**Comment by 0x0021** [comment]
``` bash
$ /opt/cisco/anyconnect/bin/vpn -s connect {address}                                                                                                                                               
Cisco AnyConnect Secure Mobility Client (version 4.10.01075) .

Copyright (c) 2004 - 2021 Cisco Systems, Inc.  All Rights Reserved.


  >> state: Disconnected
  >> state: Disconnected
  >> notice: Ready to connect.
  >> registered with local VPN subsystem.
  >> contacting host ({address}) for login information...
  >> notice: Contacting {address}.

  >> 请输入你的用户名和密码
    0) 普通用户{group 0}
    1) 管理员入口{group 1}
Group: [管理员入口] 1

Username: [xuyukun] xuyukun
xuyukun
Password:
  >> notice: Please respond to banner.

欢迎接入Rokae办公网络。
为保障网络资源安全合理利用，账号严禁外泄！

accept? [y/n]: y
  >> state: Connecting
  >> notice: Establishing VPN session...
  >> notice: The AnyConnect Downloader is performing update checks...
  >> notice: Checking for profile updates...
  >> notice: Checking for customization updates...
  >> notice: Performing any required updates...
  >> notice: The AnyConnect Downloader updates have been completed.
  >> state: Connecting
  >> notice: Establishing VPN session...
  >> notice: Establishing VPN - Initiating connection...
  >> notice: Establishing VPN - Examining system...
  >> notice: Establishing VPN - Activating VPN adapter...
  >> notice: Establishing VPN - Configuring system...
  >> notice: Establishing VPN...
  >> state: Connected
```

**Comment by ptrkstr** [comment]
Thank you. Regarding this section here:
```
  >> 请输入你的用户名和密码
    0) 普通用户{group 0}
    1) 管理员入口{group 1}
Group: [管理员入口] 1
```
Is this an input of either 0 or 1, followed by the enter key?

**Comment by 0x0021** [comment]
> Thank you. Regarding this section here:
> 
> ```
>   >> 请输入你的用户名和密码
>     0) 普通用户{group 0}
>     1) 管理员入口{group 1}
> Group: [管理员入口] 1
> ```
> 
> Is this an input of either 0 or 1, followed by the enter key?

Yes!

**Comment by ptrkstr** [comment]
Are you running macOS 12?

**Comment by 0x0021** [comment]
> 您运行的是 macOS 12 吗？

yes

**Comment by ptrkstr** [comment]
Great, I will work on this next week 😇

**Comment by 0x0021** [comment]
Thank you. I'm looking forward to it ！

**Comment by ptrkstr** [comment]
@0x0021 can you clone the [issues/0001](https://github.com/ptrkstr/QuickConnect/tree/issues/0001-GroupItem) branch, run it and let me know if everything connects?
I've hardcoded the 1 and y to the banner message for now.

**Comment by 0x0021** [comment]
```
Log output...
----------------------

Cisco AnyConnect Secure Mobility Client (version 4.10.04065) .
Copyright (c) 2004 - 2021 Cisco Systems, Inc.  All Rights Reserved.
>> state: Disconnected
>> state: Disconnected
>> notice: Ready to connect.
VPN>
>> registered with local VPN subsystem.
VPN>
>> contacting host (<server>) for login information...
>> notice: Contacting <server>.
>> 请输入你的用户名和密码（Please enter your username and password）
0) 普通用户（group0）
1) 管理员入口（group1）
Group: [管理员入口]
Username: [<username>] <username>
>> 登陆失败:  用户名或密码错误（Login failed: user name or password is wrong）
```


Log in successfully after turning off OTP verification

**Comment by ptrkstr** [comment]
Thank you for testing. To clarify, does your connection require OTP? In a previous comment, your log output looked like it doesn't require OTP, that's why I removed it in this code change.

**Comment by 0x0021** [comment]
My server is submitted by a combination of pin and otp, I hope to add otp as an option  thx!

**Comment by ptrkstr** [comment]
Ohhh I see, not a problem, I'll add it back in.
Do you get asked for OTP, after password, or after accepting banner?

**Comment by 0x0021** [comment]
otp is not a separate field submission. For example, if the password is 123456 and otp is 654321, then the final password is 123456654321

**Comment by ptrkstr** [comment]
Ahh now I understand, I will add support for that.

**Comment by ptrkstr** [comment]
@0x0021 can you pull down the latest issues/0001 and let me know if that works for you?

**Comment by 0x0021** [comment]
可以使用了，非常感谢！

**Comment by 0x0021** [comment]
Can be used, thank you very much!

**Comment by 0x0021** [comment]
It works normally, thank you!

**Comment by ptrkstr** [comment]
Glad it worked :)
I recommend forking this branch so you have your own copy as I'll remove it eventually to keep things tidy.
